services:
  - type: web
    name: whatsapp-accounts
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: whatsapp-redis
          property: connectionString
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: COMPANY_NAME
        value: Mi Empresa

databases:
  - name: whatsapp-db
    plan: free

  - name: whatsapp-redis
    type: redis
    plan: free
